library(tidyverse)
library(readxl)
library(worrms)

# Select year
year <- 2024

# Find the latest bvol file
bvol_filename <- list.files("data") %>%
  as_tibble() %>%
  filter(agrepl("NOMP_BVOL", value)) %>%
  filter(agrepl(".xlsx", value)) %>%
  filter(!agrepl("~$", value)) %>%
  filter(agrepl(year, value)) %>%
  arrange(value)

# Read current NOMP list
bvol_nomp <- read_excel(file.path("data", bvol_filename$value[nrow(bvol_filename)])) %>%
  select(-contains("NOT IMPORTED"))

# Read trophic_type
trophic_type <- read_excel(file.path("data", "trophictype_.xlsx"))

# Read Taxa worms generated by https://github.com/planktontoolbox/plankton-toolbox-taxa-worms
taxa_worms <- read_tsv(file.path("data", "taxa_worms.txt"))

scientific_name <- unique(bvol_nomp$Species)

missing_names <- scientific_name[!scientific_name %in% taxa_worms$scientific_name]

missing_taxa <- bvol_nomp %>%
  filter(Species %in% missing_names) %>%
  select(Species, AphiaID) %>%
  distinct()

worms_records <- wm_record(missing_taxa$AphiaID)

missing_taxa <- missing_taxa %>%
  mutate(species_name_to = worms_records$valid_name,
         valid_AphiaID = worms_records$valid_AphiaID,
         unacceptreason = worms_records$unacceptreason) %>%
  rename(species_name_from = Species) %>%
  relocate(species_name_to, .after = species_name_from)

write.table(missing_taxa,
            file = "output/translate_worms_additions.txt",
            sep = "\t",
            row.names = FALSE,
            col.names = TRUE,
            na = "",
            fileEncoding = "latin1",
            quote = FALSE)

species_size <- bvol_nomp %>%
  mutate(species_size = paste(Species, SizeClassNo, sep = "_")) %>%
  select(species_size) %>%
  distinct()

trophic_type <- trophic_type %>%
  mutate(species_size = paste(scientific_name, size_class, sep = "_"))

missing_trophic_type <- species_size %>%
  filter(!species_size %in% trophic_type$species_size) %>%
  mutate(scientific_name = word(species_size, 1, sep = "_"),
         size_class = word(species_size, 2, sep = "_"),
         trophic_type = NA,
         comments = NA,
         trophic_type_source = NA) %>%
  select(-species_size)

missing_blank_size_class <- unique(missing_trophic_type$scientific_name)[!paste(unique(missing_trophic_type$scientific_name), "NA", sep = "_") %in% trophic_type$species_size]

missing_blank_size_class_df <- tibble(scientific_name = missing_blank_size_class,         
                                      size_class = NA,
                                      trophic_type = NA,
                                      comments = NA,
                                      trophic_type_source = NA)

missing_trophic_type <- missing_trophic_type %>%
  rbind(missing_blank_size_class_df) %>%
  arrange(scientific_name, size_class)

write.table(missing_trophic_type,
            file = "output/trophic_type_additions.txt",
            sep = "\t",
            row.names = FALSE,
            col.names = TRUE,
            na = "",
            fileEncoding = "latin1",
            quote = FALSE)
